name: docker-publish-1

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  #push:
  #  branches: [ main ]
  #  # Publish semver tags as releases.
  #  tags: [ 'v*.*.*' ]
  #pull_request:
  #  branches: [ main ]
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty.
  REGISTRY: ghcr.io/${{ github.actor }}
  # github.repository as <account>/<repo>
  API_IMAGE_NAME: fabrikam-api
  INIT_IMAGE_NAME: fabrikam-init  
  WEB_IMAGE_NAME: fabrikam-web

jobs:
  check_changed_folders:
      name: Check modified files
      outputs:
        run_api_job: ${{ steps.check_files.outputs.run_api_job }}
        run_web_job: ${{ steps.check_files.outputs.run_web_job }}
        run_init_job: ${{ steps.check_files.outputs.run_init_job }}
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
          with:
            fetch-depth: 2

        - name: check modified files
          id: check_files
          run: |            
            echo "========== check paths of modified files =========="
            git diff --name-only HEAD^ HEAD > files.txt
            echo "::set-output name=run_api_job::false"                
            echo "::set-output name=run_web_job::false"            
            echo "::set-output name=run_init_job::false"
            while IFS= read -r file
            do
              echo $file
              if [[ $file == content-api/* ]]; then                
                echo "::set-output name=run_api_job::true"
                continue
              elif [[ $file == content-web/* ]]; then                                                  
                echo "::set-output name=run_web_job::true"
                continue
              elif [[ $file == content-init/* ]]; then                
                echo "::set-output name=run_init_job::true"
                continue
              fi
            done < files.txt
  build-api:
    runs-on: ubuntu-latest
    name: Update the API Docker image
    needs: check_changed_folders
    if: needs.check_changed_folders.outputs.run_api_job == 'true'
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      # Extract API image metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata for ${{ env.API_IMAGE_NAME }}
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image for ${{ env.API_IMAGE_NAME }}
        id: build-and-push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          file: ./content-api/Dockerfile                      # <-- Add these
          context: ./content-api                              # <-- two lines
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-init:
    runs-on: ubuntu-latest
    name: Update the Init Docker image
    needs: check_changed_folders
    if: needs.check_changed_folders.outputs.run_init_job == 'true'
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}      

      # Extract INIT image metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata for ${{ env.INIT_IMAGE_NAME }}
        id: meta-init
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.INIT_IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image for ${{ env.INIT_IMAGE_NAME }}
        id: build-and-push-init
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          file: ./content-init/Dockerfile                      # <-- Add these
          context: ./content-init                              # <-- two lines
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-init.outputs.tags }}
          labels: ${{ steps.meta-init.outputs.labels }}

  build-web:
    runs-on: ubuntu-latest
    name: Update the Web Docker image
    needs: check_changed_folders
    if: needs.check_changed_folders.outputs.run_web_job == 'true'
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      # Extract WEB image metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata for ${{ env.WEB_IMAGE_NAME }}
        id: meta-web
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.WEB_IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image for ${{ env.WEB_IMAGE_NAME }}
        id: build-and-push-web
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          file: ./content-web/Dockerfile                      # <-- Add these
          context: ./content-web                              # <-- two lines
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-web.outputs.tags }}
          labels: ${{ steps.meta-web.outputs.labels }}