version: "3.4"

services:
  init:
    build: ./content-init
    image: ghcr.io/{githubusername}/fabrikam-init:main
    depends_on:
      - mongo
    environment:
      MONGODB_CONNECTION: mongodb://mongo:27017/contentdb
